apiVersion: builtin
kind: PatchTransformer
metadata:
  name: ghcr-pull-secret
patch: |-
  - op: add
    path: /imagePullSecrets
    value:
      - name: ghcr-secret
target:
  kind: ServiceAccount
  name: (adservice|cartservice|checkoutservice|currencyservice|emailservice|frontend|loadgenerator|paymentservice|productcatalogservice|recommendationservice|shippingservice)
