
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aegisops
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/lmaimounisara-cell/devsecops-gitops-project.git
    targetRevision: HEAD
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: boutique-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
